package:
  name: elemental-backend
  version: "0.2.0dev"

source:
  git_url: https://github.com/artplusplus/elemental-backend.git
  git_rev: v0.2.0-dev

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - pytest
  imports:
    - elemental_backend

about:
  home: https://github.com/artplusplus/elemental-backend.
  summary: elemental-backend provides a data backend for elemental cms.
  license: Mozilla Public License (MPL) version 2.0
  license_file: LICENSE