package:
  name: elemental-backend
  version: "0.4.0"

source:
  path: ../

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - elemental-core
    - elemental-kinds
    - marshmallow
  run:
    - python
    - elemental-core
    - elemental-kinds
    - marshmallow

test:
  requires:
    - pytest
  imports:
    - elemental_backend

about:
  home: https://github.com/artplusplus/elemental-backend.
  summary: elemental-backend provides a data backend for elemental cms.
  license: Mozilla Public License 2.0 (MPL 2.0)
  license_file: LICENSE
