package:
  name: elemental-backend
  version: "0.3.0dev0"

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - elemental-core
    - elemental-kinds
  run:
    - python
    - elemental-core
    - elemental-kinds

test:
  requires:
    - pytest
  imports:
    - elemental_backend

about:
  home: https://github.com/artplusplus/elemental-backend.
  summary: elemental-backend provides a data backend for elemental cms.
  license: Mozilla Public License 2.0 (MPL 2.0)
  license_file: LICENSE
